import { LearningTemplate } from '../../../../../components/learning/learning-template'
import { PoissonBracketAlgebra } from '../../../../../components/viz/physics-viz/modules'

function PoissonBracketsAndFirstIntegrals() {
  const config = {
    learning: {
      groupTitle: 'Part III: Hamiltonian Mechanics and Canonical Formalism',
      category: 'Classical Mechanics',
      title: 'Poisson Brackets and First Integrals',
      subtitle: 'The algebraic structure of Hamiltonian mechanics and conserved quantities'
    },
    units: [
      {
        title: 'Poisson Brackets and First Integrals',
        subtitle: 'The algebraic structure of Hamiltonian mechanics and conserved quantities',
        cards: [
          {
            title: 'Overview',
            content: (
              <>
                <p>
                  A conserved quantity is a function on phase space that does not change along any
                  trajectory. The Poisson bracket is the tool that tells you whether a quantity is
                  conserved. It does more: it turns the set of all conserved quantities into an
                  algebra, so that brackets of two conserved quantities automatically produce a
                  third.
                </p>
                <ul className="lrn-list">
                  <li>What a Poisson bracket measures: rate of change along a flow</li>
                  <li>
                    {`The coordinate formula $\\{F, G\\} = \\sum_i \\frac{\\partial F}{\\partial q_i}\\frac{\\partial G}{\\partial p_i} - \\frac{\\partial F}{\\partial p_i}\\frac{\\partial G}{\\partial q_i}$`}
                  </li>
                  <li>
                    {`Hamilton's equations as $\\dot{F} = \\{F, H\\}$ for any observable $F$`}
                  </li>
                  <li>{`Conservation: $F$ is a first integral if and only if $\\{F, H\\} = 0$`}</li>
                  <li>
                    {"Poisson's theorem: brackets of first integrals give more first integrals"}
                  </li>
                  <li>The Jacobi identity and the Lie algebra structure</li>
                  <li>Involution and Liouville integrability</li>
                </ul>
              </>
            )
          },
          {
            title: 'What a Poisson Bracket Measures',
            content: (
              <>
                <p>
                  Take any smooth function {`$F(q, p)$`} on phase space and any Hamiltonian{' '}
                  {`$H(q, p)$`}. The Hamiltonian generates a flow: starting from any point{' '}
                  {`$(q, p)$`}, the system moves along the unique trajectory given by Hamilton's
                  equations. Call this flow {`$g^t_H$`}: the position in phase space after time{' '}
                  {`$t$`}.
                </p>
                <p>
                  How fast is {`$F$`} changing right now, as the system moves under {`$H$`}? The
                  answer is the <strong>Poisson bracket</strong> {`$\\{F, H\\}$`}:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\{F, H\\}(x) = \\left.\\frac{d}{dt}\\right|_{t=0} F\\bigl(g^t_H(x)\\bigr)$$`}</span>
                </div>
                <p>
                  This is the coordinate-free definition. It measures the instantaneous rate of
                  change of {`$F$`} along the phase flow generated by {`$H$`}. No coordinates
                  required.
                </p>
                <div className="lrn-insight">
                  <p>
                    {`$\\{F, H\\}$`} asks: sitting at a point in phase space and watching the system
                    evolve under {`$H$`}, how fast does {`$F$`} change? If the answer is zero
                    everywhere, {`$F$`} is a conserved quantity.
                  </p>
                </div>
                <p>
                  The bracket is antisymmetric: {`$\\{F, H\\} = -\\{H, F\\}$`}. Swapping the two
                  functions flips the sign. This follows from the definition: the rate at which{' '}
                  {`$F$`} changes along {`$H$`}'s flow equals minus the rate at which {`$H$`}{' '}
                  changes along {`$F$`}'s flow.
                </p>
              </>
            )
          },
          {
            title: 'The Coordinate Formula',
            content: (
              <>
                <p>
                  In canonical coordinates {`$(q_1, \\ldots, q_n, p_1, \\ldots, p_n)$`}, the Poisson
                  bracket takes an explicit form. Differentiate {`$F$`} along the trajectory using
                  the chain rule and substitute Hamilton's equations{' '}
                  {`$\\dot{q}_i = \\frac{\\partial H}{\\partial p_i}$`} and{' '}
                  {`$\\dot{p}_i = -\\frac{\\partial H}{\\partial q_i}$`}:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\{F, G\\} = \\sum_{i=1}^{n} \\left( \\frac{\\partial F}{\\partial q_i}\\frac{\\partial G}{\\partial p_i} - \\frac{\\partial F}{\\partial p_i}\\frac{\\partial G}{\\partial q_i} \\right)$$`}</span>
                </div>
                <p>
                  Each term pairs the rate of change of {`$F$`} in the {`$q_i$`} direction with the
                  rate of change of {`$G$`} in the paired {`$p_i$`} direction, minus the reversed
                  cross term. The alternating signs come from the symplectic structure: position and
                  momentum coordinates are paired with opposite roles.
                </p>
                <p>Three properties follow directly from this formula:</p>
                <ul className="lrn-list">
                  <li>
                    <strong>Antisymmetry:</strong> {`$\\{F, G\\} = -\\{G, F\\}$`}. In particular,{' '}
                    {`$\\{F, F\\} = 0$`} for any {`$F$`}.
                  </li>
                  <li>
                    <strong>Linearity:</strong> {`$\\{aF + bG, H\\} = a\\{F, H\\} + b\\{G, H\\}$`}{' '}
                    for constants {`$a, b$`}.
                  </li>
                  <li>
                    <strong>Leibniz rule:</strong> {`$\\{FG, H\\} = F\\{G, H\\} + G\\{F, H\\}$`}.
                    The bracket acts like a derivative on products.
                  </li>
                </ul>
                <p>The fundamental brackets between the coordinates themselves are:</p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\{q_i, p_j\\} = \\delta_{ij}, \\qquad \\{q_i, q_j\\} = 0, \\qquad \\{p_i, p_j\\} = 0$$`}</span>
                </div>
                <p>
                  {`$\\delta_{ij}$`} is 1 when {`$i = j$`} and 0 otherwise. Positions bracket to
                  zero among themselves, momenta bracket to zero among themselves, and each position
                  brackets with its conjugate momentum to give 1. Any coordinate change that
                  preserves these three relations is a canonical transformation.
                </p>
              </>
            )
          },
          {
            title: "Hamilton's Equations as Bracket Equations",
            content: (
              <>
                <p>
                  The Poisson bracket unifies all of Hamiltonian mechanics into one statement. For
                  any observable {`$F(q, p, t)$`}, any smooth function on phase space, its total
                  rate of change along a trajectory is:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\dot{F} = \\{F, H\\} + \\frac{\\partial F}{\\partial t}$$`}</span>
                </div>
                <p>
                  The {`$\\frac{\\partial F}{\\partial t}$`} term is nonzero only when {`$F$`} is
                  written with an explicit {`$t$`}. For most observables, position, momentum,
                  energy, angular momentum, there is no explicit time dependence, so{' '}
                  {`$\\dot{F} = \\{F, H\\}$`}.
                </p>
                <p>
                  {"Hamilton's canonical equations are special cases. Set"} {`$F = q_i$`}:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\dot{q}_i = \\{q_i, H\\} = \\sum_j \\frac{\\partial q_i}{\\partial q_j}\\frac{\\partial H}{\\partial p_j} = \\frac{\\partial H}{\\partial p_i}$$`}</span>
                </div>
                <p>Set {`$F = p_i$`}:</p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\dot{p}_i = \\{p_i, H\\} = -\\sum_j \\frac{\\partial p_i}{\\partial p_j}\\frac{\\partial H}{\\partial q_j} = -\\frac{\\partial H}{\\partial q_i}$$`}</span>
                </div>
                <p>
                  The original pair of equations falls out as two instances of one general
                  principle. Any quantity evolves by taking its bracket with the Hamiltonian.
                </p>
                <div className="lrn-callout">
                  <p>
                    This is why the Hamiltonian is the generator of time evolution. The map{' '}
                    {`$\\{\\cdot,\\, H\\}$`} is the operation of differentiation along the flow.
                    Knowing {`$H$`} and knowing how to compute brackets is knowing everything about
                    the dynamics.
                  </p>
                </div>
              </>
            )
          },
          {
            title: 'First Integrals and Conservation',
            content: (
              <>
                <p>
                  A <strong>first integral</strong> (also: conserved quantity, constant of motion)
                  is a function {`$F(q, p)$`} that stays constant along every trajectory. The
                  condition is:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\{F, H\\} = 0$$`}</span>
                </div>
                <p>
                  This follows directly from {`$\\dot{F} = \\{F, H\\}$`}: when the bracket vanishes
                  everywhere on phase space, {`$\\dot{F} = 0$`} along every trajectory, so {`$F$`}{' '}
                  never changes.
                </p>
                <p>
                  <strong>Energy is always conserved.</strong> By antisymmetry,{' '}
                  {`$\\{H, H\\} = -\\{H, H\\}$`}, so {`$\\{H, H\\} = 0$`}. The Hamiltonian commutes
                  with itself under the bracket. Every Hamiltonian system conserves its own energy,
                  regardless of what {`$H$`} looks like.
                </p>
                <p>Common first integrals and their origins:</p>
                <ul className="lrn-list">
                  <li>
                    <strong>Energy</strong> {`$H$`}: conserved whenever {`$H$`} has no explicit time
                    dependence.
                  </li>
                  <li>
                    <strong>Linear momentum</strong> {`$p_i$`}: conserved whenever {`$q_i$`} is
                    cyclic (does not appear in {`$H$`}).
                  </li>
                  <li>
                    <strong>Angular momentum</strong> {`$L = q_1 p_2 - q_2 p_1$`}: conserved
                    whenever {`$H$`} is rotationally symmetric.
                  </li>
                  <li>
                    <strong>Runge-Lenz vector</strong> (Kepler problem): a conserved vector specific
                    to the inverse-square-law potential that explains why all Kepler orbits are
                    closed.
                  </li>
                </ul>
                <div className="lrn-insight">
                  <p>
                    Every symmetry of {`$H$`} produces a first integral. This is Noether's theorem
                    in Hamiltonian language. The condition {`$\\{F, H\\} = 0$`} means both that{' '}
                    {`$F$`} is conserved and that {`$F$`} generates a symmetry of {`$H$`}. The two
                    statements are identical.
                  </p>
                </div>
              </>
            )
          },
          {
            title: "Poisson's Theorem",
            content: (
              <>
                <p>
                  Suppose you have found two first integrals {`$F_1$`} and {`$F_2$`}, both
                  satisfying {`$\\{F_1, H\\} = 0$`} and {`$\\{F_2, H\\} = 0$`}. Is their bracket{' '}
                  {`$\\{F_1, F_2\\}$`} also conserved?
                </p>
                <div className="lrn-definition">
                  <span className="lrn-definition-term">{"Poisson's Theorem"}</span>
                  <div className="lrn-definition-desc">
                    <p>
                      If {`$F_1$`} and {`$F_2$`} are both first integrals of {`$H$`}, then{' '}
                      {`$\\{F_1, F_2\\}$`} is also a first integral of {`$H$`}.
                    </p>
                  </div>
                </div>
                <p>
                  <strong>Proof.</strong> Apply the Jacobi identity to {`$F_1$`}, {`$F_2$`}, {`$H$`}
                  :
                </p>
                <div className="lrn-eq">
                  <span>{`$$\\{\\{F_1, F_2\\},\\, H\\} + \\{\\{F_2, H\\},\\, F_1\\} + \\{\\{H, F_1\\},\\, F_2\\} = 0$$`}</span>
                </div>
                <p>
                  Since {`$\\{F_2, H\\} = 0$`} by assumption, the second term vanishes. Since{' '}
                  {`$\\{H, F_1\\} = -\\{F_1, H\\} = 0$`}, the third term vanishes too. Therefore{' '}
                  {`$\\{\\{F_1, F_2\\}, H\\} = 0$`}. Q.E.D.
                </p>
                <p>
                  <strong>Practical use.</strong> Start with two known first integrals. Take their
                  bracket to get a third. Take the bracket of that with each of the originals to get
                  more. Continue until no new independent integrals appear. In a well-behaved system
                  this process terminates: the algebra of first integrals closes on itself.
                </p>
                <div className="lrn-callout">
                  <p>
                    {`$\\{F_1, F_2\\}$`} is often a function of {`$F_1$`} and {`$F_2$`}
                    themselves, adding nothing new. When it is genuinely independent, you have found
                    a new symmetry. The closure of the algebra of first integrals is what separates
                    integrable systems from chaotic ones.
                  </p>
                </div>
              </>
            )
          },
          {
            title: 'The Jacobi Identity and the Lie Algebra',
            content: (
              <>
                <p>
                  The Poisson bracket satisfies one more identity beyond antisymmetry and linearity.
                  For any three functions {`$A$`}, {`$B$`}, {`$C$`} on phase space:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\{\\{A, B\\}, C\\} + \\{\\{B, C\\}, A\\} + \\{\\{C, A\\}, B\\} = 0$$`}</span>
                </div>
                <p>
                  This is the <strong>Jacobi identity</strong>. Take three functions and bracket
                  them in a cyclic pattern. The three results always sum to zero.
                </p>
                <p>
                  A vector space with an antisymmetric, bilinear operation satisfying the Jacobi
                  identity is called a <strong>Lie algebra</strong>. The smooth functions on phase
                  space, equipped with the Poisson bracket, form a Lie algebra.
                </p>
                <p>
                  There is a second Lie algebra in the picture: vector fields on phase space,
                  equipped with the Lie bracket. The map sending a function {`$H$`} to the
                  Hamiltonian vector field it generates is a Lie algebra homomorphism:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$[X_F,\\, X_G] = X_{\\{F,\\, G\\}}$$`}</span>
                </div>
                <p>
                  Here {`$X_F$`} is the Hamiltonian vector field generated by {`$F$`}, and{' '}
                  {`$[X_F, X_G]$`} is the Lie bracket of the two vector fields. The commutator of
                  the vector fields corresponds exactly to the Poisson bracket of the generating
                  functions.
                </p>
                <div className="lrn-insight">
                  <p>
                    The Jacobi identity is the reason {"Poisson's"} theorem works. It is built into
                    the symplectic structure of phase space. Every symplectic manifold automatically
                    carries a Lie algebra on its functions, with the Poisson bracket as the product.
                  </p>
                </div>
                <PoissonBracketAlgebra />
              </>
            )
          },
          {
            title: 'Involution and Liouville Integrability',
            content: (
              <>
                <p>
                  Two first integrals {`$F_1$`} and {`$F_2$`} are in <strong>involution</strong> if
                  their bracket vanishes:
                </p>
                <div className="lrn-eq lrn-eq-display">
                  <span>{`$$\\{F_1, F_2\\} = 0$$`}</span>
                </div>
                <p>
                  Involution means the flows generated by {`$F_1$`} and {`$F_2$`} commute: flowing
                  under {`$F_1$`} for time {`$s$`} then under {`$F_2$`} for time {`$t$`} gives the
                  same result as doing them in the reverse order.
                </p>
                <div className="lrn-definition">
                  <span className="lrn-definition-term">Liouville Integrability</span>
                  <div className="lrn-definition-desc">
                    <p>
                      A Hamiltonian system with {`$n$`} degrees of freedom is Liouville integrable
                      if there exist {`$n$`} independent first integrals {`$F_1, \\ldots, F_n$`}{' '}
                      (including {`$H$`} itself) that are pairwise in involution:{' '}
                      {`$\\{F_i, F_j\\} = 0$`} for all {`$i, j$`}.
                    </p>
                  </div>
                </div>
                <p>
                  Why does this solve the system? The {`$n$`} commuting flows give {`$n$`}{' '}
                  independent directions in phase space that can be integrated separately. Together
                  they foliate phase space into {`$n$`}-dimensional tori. On each torus, the motion
                  is uniform in {`$n$`} independent directions: exactly the action-angle variable
                  picture.
                </p>
                <p>
                  The Hamilton-Jacobi method supplies the connection: when {`$n$`} involutory
                  integrals exist, the HJ equation separates. The {`$n$`} integrals supply the{' '}
                  {`$n$`} constants in a complete integral {`$S(q, Q, t)$`}. The system is solved by
                  quadratures.
                </p>
                <ul className="lrn-list">
                  <li>
                    <strong>Kepler problem</strong> ({`$n = 3$`}): energy {`$H$`}, total angular
                    momentum {`$|L|^2$`}, one component {`$L_z$`}, all three in involution.
                  </li>
                  <li>
                    <strong>Harmonic oscillator</strong> ({`$n$`} dimensions): the energies in each
                    mode {`$E_i = \\frac{p_i^2}{2} + \\frac{\\omega_i^2 q_i^2}{2}$`} are pairwise in
                    involution.
                  </li>
                  <li>
                    <strong>Rigid body</strong> (Euler equations): three angular momentum components
                    are first integrals; only two of the three are in involution, requiring a
                    different analysis.
                  </li>
                </ul>
                <div className="lrn-callout">
                  <p>
                    Most Hamiltonian systems are <em>not</em> Liouville integrable. A generic
                    perturbation of an integrable system destroys the involutory integrals, and the
                    tori break into chaotic trajectories (KAM theory). The integrable systems,
                    Kepler, harmonic oscillator, rigid body, Toda lattice, are rare and special.
                    That rarity is exactly why they have been studied so thoroughly.
                  </p>
                </div>
              </>
            )
          }
        ]
      }
    ],
    customCss: `.MafsView { --mafs-bg: transparent; --mafs-fg: rgba(240,240,250,1); --mafs-line-color: rgba(240,240,250,0.15); }`
  }
  return <LearningTemplate config={config} />
}

export default PoissonBracketsAndFirstIntegrals
